version: "3.8"

services:
  server:
    image: votogether:server
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - ../../images:/home/static/images
    command: tail -f /dev/null
