name: Test When Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 환경 설정
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle 테스트 실행
        run: ./gradlew --info test

      - name: 테스트 결과 PR 코멘트 등록
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
